### ISSUE TITLE
Implement autocompletion search

### ISSUE THREAD

**Issue by tschaka1904** [EBI-IntAct/intact-view#1]
As one of the search-types require, we want to offer a suggestion/autocompletion search. Foundation (the ebi supported style framework) doesn't offer components to allow a good access to implement the feature easily. Resources like bootstrap offer a typeahead library, which allows a simple plug and play and further more it offers a angular integration as well. This is the first version of the autocompletion: 
![sneak_peak_newia_search](https://user-images.githubusercontent.com/5269116/27138169-c8bbab42-5117-11e7-9318-a4bd898c59bf.gif)

**Comment by elisabetb** [comment]
Done!!!
